### ISSUE TITLE
Server exceptions and resolutions.

### ISSUE THREAD

**Issue by fredkingham** [odonto/odonto#186]
A list of exceptions we have/need to be resolved. This has been pruned slightly pruned for what (I hope) are obvious solved issues, e.g. date formatting or required fields.

- [ ] @062 | Date of Acceptance is a future date

- [ ] @086 | Date of completion is prior to the date of acceptance.

- [ ] @120 | Invalid dentist declaration.

- [ ] @124 | Invalid exemption/remission code.

- [ ] @125 | Expectant or Nursing mother but patient is male

- [x] @126 | Age exemption invalid for date of birth.

- [ ] @162 | Invalid values following Orthodontic extractions, BPE or Visible Plaque scores

- [ ] @192 | Invalid treatment quantity accompanyingClinical Dataset or KPI

- [x] @207 | Duplicate transmission of serial number <1> Please contact System Supplier
- Should be impossible because of serialization (ie the transmission_id should always be unique)

- [ ] @212 | Claim already received. If you wish original to be deleted and this claim substituted, please retransmit with appropriate SQ indicator. Otherwise do not retransmit

- [x] @254 | ‘Under 18’ exemption (16 for IOM) invalid for date of birth.

- [x] @256 | Under 18 exemption must be present for patients under 18 (16 for IOM).

- [ ] @283 | Date of completion is after the date of receipt

- [ ] @285 | Treatment dates are outside the period of the contract or the performers tenure within that contract

- [ ] @306 | Invalid patient charge band

- [ ] @317 | No aesthetic component to accompany IOTN value of 3

- [ ] @318 | Conflicting assessment and/or completion items

- [ ] @319 | Free Repair/Replacement with no treatment band 2,3 or urgent

- [ ] @320 | Further Treatment claim with no treatment band

- [ ] @321 | Incomplete treatment band not consistent with treatment band claimed

- [x] @324 | Date Appliance fitted is prior to the date of assessment

- [ ] @329 | KPI treatment codes on a non-PDS Plus contract

- [ ] @330 | Schedule Query Indicator claim but original cannot be found

- [ ] @331 | Schedule Query Indicatorclaim but original has already been deleted or is in error

- [ ] @332 | Schedule Query Indicator Deletion but original cannot be found

- [ ] @333 | Schedule query not carried out. Original claim cannot be deleted as it is for a different provider

- [ ] @334 | Patient email address, mobile phone number or patient declined indicator must be present

- [ ] @335 | Mandatory commissioner approval indicator missing for adult orthodontic patient

- [ ] @336 | Mandatory IOTN code missing

- [ ] @337 | Mandatory date of referral missing

- [x] @338 | No NHS number has been entered

- [ ] @339 | Mandatory Treatment Proposed indicator missing

- [ ] @340 | Mandatory Treatment Completed/Abandoned/Discontinued indicator missing

- [ ] 103 | Invalid or missing Date of Acceptance or Completion

- [ ] 109 | Remission or Exemption box error

- [ ] 115 | Treatment code not valid according to the claim date

- [ ] 125 | Unacceptable combinations of treatments on a claim

- [ ] 127 | Referral for Advanced Mandatory Services and no treatment band

- [ ] 128 | Inappropriate quantity associated with treatment code

- [ ] 401 | Claim overlaps or duplicates an existing claim for the same patient with the same contract, provider or performer

- [ ] 509 | Performer is on authorised leave at the treatment start and end dates

- [ ] 804 | Treatment code appears more than once on the same claim

- [ ] 858 | Date missing on an orthodontic claim

- [ ] 862 | Invalid or inconsistent dates on an FP17O

- [ ] 863 | Inappropriate patient's charge accompanying Reg 11 (Reg 9 in Isle of Man) claim

- [ ] 864 | Inappropriate patient's charge accompanying an orthodontic Reg 11 (Reg 9 in Isle of Man) claim

- [ ] 865 | Ortho Assessment accompanying a Reg 11 claim (Reg 9 in Isle of Man)

- [ ] 867 | Patient charge present on a referral claim where Domiciliary Services or Sedation Services absent

- [x] 868 | 1st line of patient's address missing

- [ ] 869 | Further Treatment Within 2 Months invalid

- [ ] 870 | Free Repair/Replacement Within 12 Months invalid

- [ ] 895 | FP17O assessment where previous  claim is assessment/appliance fitted

- [ ] 896 | FP17O completion/abandoned/discontinued claim where previous claim is Ortho completion

- [ ] 897 | Free exam exemption where patients age is not appropriate

- [ ] 898 | Advanced Mandatory Services (9316) on claim dated after 1/4/14 England 1/5/14 Wales

- [ ] 899 | E-mail address invalid format

**Comment by davidmiller** [comment]
All resolved now.

**Comment by 207** [comment]
Good to hear
