### ISSUE TITLE
Details from the companion document should be accessible as popovers or links 

### ISSUE THREAD

**Issue by pacharanero** [odonto/odonto#23]
* There is explanatory information in the companion document https://drive.google.com/drive/u/0/folders/1fiVMMcKXeU7KpbtVXiMUIbbHUxl-_Wvl which provides more detail on each of the fields in the FP17

* we should provide a way to view this information that doesn't break the workflow

* a popover https://getbootstrap.com/docs/3.3/javascript/#popovers might be a nice way of doing this in-page

**Comment by davidmiller** [comment]
We might, but unlikely short term...
