### ISSUE TITLE
Login screen says 'Log in to manage referrals'

### ISSUE THREAD

**Issue by pacharanero** [odonto/odonto#25]
![image](https://user-images.githubusercontent.com/2348385/36963818-9db6867e-204c-11e8-94c6-b70cf8eb1bf3.png)

I guess this is coming from `odontotheme` and was relevant to the RMS usecase but not this one

**Comment by davidmiller** [comment]
I think this is no longer the case in odontotheme master as of https://github.com/odonto/opal-odontotheme/commit/041137758b14a7c33ffa503a015072666f3ed9ab - maybe pull (or reinstall if you're not running from `setup.py develop` ?

**Comment by pacharanero** [comment]
OK apols

**Comment by davidmiller** [comment]
Not at all - no apols required ! 
I only noticed this myself yesterday eve :) 

It's exactly the kind of thing you can look right past!

**Comment by pacharanero** [comment]
Yep, pulled from master and it's fixed

![image](https://user-images.githubusercontent.com/2348385/36967857-c6bc318e-2058-11e8-823c-53f345c5642e.png)
