### ISSUE TITLE
Country Of Birth doesn't appear to be on the FP17 form at all

### ISSUE THREAD

**Issue by pacharanero** [odonto/odonto#26]
https://www.nhsbsa.nhs.uk/sites/default/files/2017-04/20160216_FP17_Proof_Sample.pdf

perhaps it should be removed from the form

**Comment by pacharanero** [comment]
Related: Ethnicity is recorded but only as part of the patient's declaration on the reverse

**Comment by davidmiller** [comment]
We've now removed these from the 'register patient' and demographics forms
