### ISSUE TITLE
settings decisions

### ISSUE THREAD

**Issue by fredkingham** [odonto/odonto#42]
At present the standard for all opal projects has been to use an override of local settings.

ie the settings.jinja has

```
try:
    from local_settings import *
except ImportError:
    pass
```

which allows for adding in prod dbs etc.

Previous projects I have worked on have had a settings directory with `base.py`, `dev.py`, `test.py`, `prod.py`.

I think the `base.py` approach is the norm.

Is it worth changing to the latter approach?

**Comment by lamby** [comment]
Probably makes sense to keep to whatever Opal does by default to ensure it matches docs for newcomers, etc.

**Comment by davidmiller** [comment]
Whatever we're doing in the repo as of today is whatever we decided :)
