### ISSUE TITLE
Front end form changes

### ISSUE THREAD

**Issue by fredkingham** [odonto/odonto#65]
- [x] The pathway is a bit wider than the page width, both within frame and without the frame
- [x] Change the sex radio buttons to bootstrap radio buttons
- [x] Remove the 'Part x' prefix on the last question
- [x] Remove the duplicate choose a Band (once via a select, once via bootstrap radio)
- [x] Make sure the Band category field is after the part where you decide what to do
- [ ] Add a patient needs to pay box at the beginning of the form
- [x] Examintion should be the first option given
- [x] When a nurse is logged in remove the declaration step at the end

**Comment by davidmiller** [comment]
These are done / de-scoped
