### ISSUE TITLE
Marital Status dropdown

### ISSUE THREAD

**Issue by davidmiller** [odonto/odonto#80]
Can we figure out what's going on with this?

```
Hello

I have just tried to enter details of a patient onto the system and have encountered 2 errors:-

The marital statue drop down box isn’t bringing up any options and although it has the “Sex” heading there are no options to mark male/female.

I have completed the rest of the record and saved it

Thanks
```

**Comment by fredkingham** [comment]
This was because
a) We had a select box for title but no lookup list. On heroku we'd changed this to an input as its not validated by fp17
b) We hadn't loaded lookup lists for sex. This has already been resolved.
